version: '3.7'
services:
  simple_cinema_postgres:
    platform: linux/amd64
    container_name: simple_cinema_postgres
    image: postgres
    restart: always
    volumes:
      - simple_cinema_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432"

  simple_cinema_goose:
    container_name: simple_cinema_goose
    platform: linux/amd64
    image: gomicro/goose
    command: goose up -dir /migration/postgres
    restart: "on-failure"
    volumes:
      - ./migration/postgres:/migration/postgres
      - .env:/.env
    environment:
      GOOSE_DBSTRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@simple_cinema_postgres:5432
      GOOSE_DRIVER: postgres
    depends_on:
      - "simple_cinema_postgres"

  simple_cinema_redis:
    container_name: simple_cinema_redis
    image: redis
    restart: always
    ports:
      - "6379"

  simple_cinema:
    container_name: simple_cinema
    image: simple_cinema
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/config
    ports:
      - "9990:9990"
    depends_on:
      - "simple_cinema_postgres"
      - "simple_cinema_redis"
      - "simple_cinema_goose"
volumes:
  simple_cinema_data:
  simple_cinema_migration: